### ISSUE TITLE
verify ownership of flatpak on flathub.org

### ISSUE THREAD

**Issue by renner0e** [flathub/com.github.qarmin.czkawka#21]
Verify the ownership of the flatpak like [firefox](https://flathub.org/apps/org.mozilla.firefox).

It adds one more layer of trust for the user (This app is actually by the original devs and can be trusted).

**Comment by qarmin** [comment]
![Screenshot from 2023-10-14 17-22-11](https://github.com/flathub/com.github.qarmin.czkawka/assets/41945903/b2904dd7-0585-40ae-a75a-4425008a4b00)
